from dbus.types import String, UInt32

from telepathy.constants import (
    CONNECTION_PRESENCE_STATUS_AVAILABLE,
    CONNECTION_PRESENCE_STATUS_AWAY,
    CONNECTION_PRESENCE_STATUS_DND,
    CONNECTION_PRESENCE_STATUS_EXTENDED_AWAY,
    CONNECTION_PRESENCE_STATUS_OFFLINE,
    CONNECTION_PRESENCE_STATUS_PSTN,
    CONNECTION_PRESENCE_STATUS_UNKNOWN,
    CONNECTION_PRESENCE_TYPE_AVAILABLE,
    CONNECTION_PRESENCE_TYPE_AWAY,
    CONNECTION_PRESENCE_TYPE_BUSY,
    CONNECTION_PRESENCE_TYPE_EXTENDED_AWAY,
    CONNECTION_PRESENCE_TYPE_OFFLINE,
    CONNECTION_PRESENCE_TYPE_UNSET,
    HANDLE_TYPE_CONTACT,
)
from telepathy.interfaces import (
    CHANNEL,
    CHANNEL_TYPE_TEXT,
    CONNECTION_INTERFACE_ALIASING,
    CONNECTION_INTERFACE_AVATARS,
    CONNECTION_INTERFACE_CONTACT_GROUPS,
    CONNECTION_INTERFACE_CONTACT_LIST,
    CONNECTION_INTERFACE_CONTACTS,
    CONNECTION_INTERFACE_REQUESTS,
    CONNECTION_INTERFACE_SIMPLE_PRESENCE,
)
from telepathy.server import (
    Protocol,
    ProtocolInterfaceAvatars,
    ProtocolInterfacePresence,
)

from skykit import PROTOCOL, AVATAR_MIME
from skykit.connection import SkykitConnection


__all__ = (
    'SkykitProtocol',
)


class SkykitProtocol(Protocol, ProtocolInterfaceAvatars, ProtocolInterfacePresence):
    
    _proto = PROTOCOL
    _english_name = PROTOCOL.capitalize()
    _icon = "im-%s" % PROTOCOL
    _vcard_field = "im-%s" % PROTOCOL

    _mandatory_parameters = {
        'account': 's',
        'password': 's',
    }

    _secret_parameters = set([
        'password',
        ])

    _requestable_channel_classes = [
        (
            {
                CHANNEL + '.ChannelType': String(CHANNEL_TYPE_TEXT),
                CHANNEL + '.TargetHandleType': UInt32(HANDLE_TYPE_CONTACT),
            },
            [
                CHANNEL + '.TargetHandle',
                CHANNEL + '.TargetID',
            ]
        ),
    ]

    _supported_interfaces = [
        CONNECTION_INTERFACE_ALIASING,
        CONNECTION_INTERFACE_AVATARS,
        CONNECTION_INTERFACE_CONTACT_GROUPS,
        CONNECTION_INTERFACE_CONTACT_LIST,
        CONNECTION_INTERFACE_CONTACTS,
        CONNECTION_INTERFACE_REQUESTS,
        CONNECTION_INTERFACE_SIMPLE_PRESENCE,
    ]

    _statuses = {
        CONNECTION_PRESENCE_STATUS_AVAILABLE: (
            CONNECTION_PRESENCE_TYPE_AVAILABLE,
            True,
            True,
        ),
        CONNECTION_PRESENCE_STATUS_OFFLINE: (
            CONNECTION_PRESENCE_TYPE_OFFLINE,
            True,
            True,
        ),
    }

    _to_telepathy = {
        'AWAY': CONNECTION_PRESENCE_STATUS_AWAY,
        'AWAY_FROM_MOBILE': CONNECTION_PRESENCE_STATUS_AWAY,
        'BLOCKED': CONNECTION_PRESENCE_STATUS_OFFLINE,
        'BLOCKED_SKYPEOUT': CONNECTION_PRESENCE_STATUS_OFFLINE,
        'CONNECTING': CONNECTION_PRESENCE_STATUS_OFFLINE,
        'DO_NOT_DISTURB': CONNECTION_PRESENCE_STATUS_DND,
        'DO_NOT_DISTURB_FROM_MOBILE': CONNECTION_PRESENCE_STATUS_DND,
        'INVISIBLE': CONNECTION_PRESENCE_STATUS_OFFLINE,
        'NOT_AVAILABLE': CONNECTION_PRESENCE_STATUS_EXTENDED_AWAY,
        'NOT_AVAILABLE_FROM_MOBILE': CONNECTION_PRESENCE_STATUS_EXTENDED_AWAY,
        'OFFLINE': CONNECTION_PRESENCE_STATUS_OFFLINE,
        'OFFLINE_BUT_VM_ABLE': CONNECTION_PRESENCE_STATUS_OFFLINE,
        'OFFLINE_BUT_CF_ABLE': CONNECTION_PRESENCE_STATUS_OFFLINE,
        'ONLINE': CONNECTION_PRESENCE_STATUS_AVAILABLE,
        'ONLINE_FROM_MOBILE': CONNECTION_PRESENCE_STATUS_AVAILABLE,
        'PENDINGAUTH': CONNECTION_PRESENCE_STATUS_OFFLINE,
        'SKYPE_ME': CONNECTION_PRESENCE_STATUS_AVAILABLE,
        'SKYPE_ME_FROM_MOBILE': CONNECTION_PRESENCE_STATUS_AVAILABLE,
        'SKYPEOUT': CONNECTION_PRESENCE_STATUS_PSTN,
        'UNKNOWN': CONNECTION_PRESENCE_STATUS_UNKNOWN,
    }

    _to_telepathy_type = {
        'AWAY': CONNECTION_PRESENCE_TYPE_AWAY,
        'AWAY_FROM_MOBILE': CONNECTION_PRESENCE_TYPE_AWAY,
        'CONNECTING': CONNECTION_PRESENCE_TYPE_OFFLINE,
        'BLOCKED': CONNECTION_PRESENCE_TYPE_OFFLINE,
        'BLOCKED_SKYPEOUT': CONNECTION_PRESENCE_TYPE_OFFLINE,
        'DO_NOT_DISTURB': CONNECTION_PRESENCE_TYPE_BUSY,
        'DO_NOT_DISTURB_FROM_MOBILE': CONNECTION_PRESENCE_TYPE_BUSY,
        'INVISIBLE': CONNECTION_PRESENCE_TYPE_OFFLINE,
        'NOT_AVAILABLE': CONNECTION_PRESENCE_TYPE_EXTENDED_AWAY,
        'NOT_AVAILABLE_FROM_MOBILE': CONNECTION_PRESENCE_TYPE_EXTENDED_AWAY,
        'OFFLINE': CONNECTION_PRESENCE_TYPE_OFFLINE,
        'OFFLINE_BUT_VM_ABLE': CONNECTION_PRESENCE_TYPE_OFFLINE,
        'OFFLINE_BUT_CF_ABLE': CONNECTION_PRESENCE_TYPE_OFFLINE,
        'ONLINE': CONNECTION_PRESENCE_TYPE_AVAILABLE,
        'ONLINE_FROM_MOBILE': CONNECTION_PRESENCE_TYPE_AVAILABLE,
        'PENDINGAUTH': CONNECTION_PRESENCE_TYPE_OFFLINE,
        'SKYPE_ME': CONNECTION_PRESENCE_TYPE_AVAILABLE,
        'SKYPE_ME_FROM_MOBILE': CONNECTION_PRESENCE_TYPE_AVAILABLE,
        'SKYPEOUT': CONNECTION_PRESENCE_TYPE_AVAILABLE,
        'UNKNOWN': CONNECTION_PRESENCE_TYPE_UNSET,
    }

    _supported_avatar_mime_types = [AVATAR_MIME]

    def __init__(self, connection_manager):
        Protocol.__init__(self, connection_manager, PROTOCOL)
        ProtocolInterfaceAvatars.__init__(self)
        ProtocolInterfacePresence.__init__(self)

    def create_connection(self, connection_manager, parameters):
        return SkykitConnection(self, connection_manager, parameters)
